// CSS Imports
import "./Profile.css";
// All other Imports
import { useEffect, useState } from "react";
import { getTaskByUserId } from "../../services/taskFetcher";
import { ProgressBar } from "react-bootstrap";

export const YesterdayStatistics = () => {
  const [userTasks, setUserTasks] = useState([]);
  const [prevDayTasks, setPrevDayTasks] = useState([]);

  const userObject = JSON.parse(localStorage.getItem("habits_user"));
  const userId = userObject.id;

  const fetchTasks = () => {
    getTaskByUserId(userId).then((data) => {
      setUserTasks(data);
    });
  };

  useEffect(() => {
    fetchTasks();
  }, [userId]);

  useEffect(() => {
    const getPrevDayDateString = () => {
      const date = new Date();

      date.setDate(date.getDate() - 1);

      return date.toISOString().slice(0, 10);
    };

    const prevDayDateString = getPrevDayDateString();

    const filteredTasks = userTasks.filter((task) => {
      if (task.dateCreated) {
        const taskDateString = new Date(task.dateCreated).toISOString().slice(0, 10);
        return taskDateString === prevDayDateString;
      }
      return false;
    });

    setPrevDayTasks(filteredTasks);
  }, [userTasks]);

  const getDailyProgress = () => {
    const allTaskCount = prevDayTasks.length;
    const completedTask = prevDayTasks.filter((task) => task.completedStatus);
    const completedCount = completedTask.length;

    if (allTaskCount === 0) {
      return 0;
    }
    const taskRatio = completedCount / allTaskCount;
    return taskRatio;
  };

  const dailyPercentage = () => {
    const ratio = getDailyProgress();
    const percentage = ratio * 100;

    return parseFloat(percentage).toFixed(1);
  };
  return (
    <div className="stat-container">
      <h2 className="data-text">Yesterday</h2>
      <div>{dailyPercentage()}% Completed</div>
      <ProgressBar className="stats-progress" now={dailyPercentage()}/>
      <p>({prevDayTasks.filter(task => task.completedStatus).length} / {prevDayTasks.length})</p>
    </div>
  );
};

// Yesterday's timestamp can be generated by filtering for 100% completion of all task and displaying the completed time of the last final task