// CSS Imports
import "./UserStats.css";
// All other Imports
import { useEffect, useState } from "react";
import { getTaskByUserId } from "../../services/taskFetcher";
import { ProgressBar } from "react-bootstrap";

export const YesterdayStatistics = () => {
  const [userTasks, setUserTasks] = useState([]);
  const [prevDayTasks, setPrevDayTasks] = useState([]);

  const userObject = JSON.parse(localStorage.getItem("habits_user"));
  const userId = userObject.id;

  const fetchTasks = () => {
    getTaskByUserId(userId).then((data) => {
      setUserTasks(data);
    });
  };

  useEffect(() => {
    fetchTasks();
  }, [userId]);

  useEffect(() => {
    const getYesterdayDateString = () => {
      const d = new Date();
      d.setDate(d.getDate() -1)

      const year = d.getFullYear();
      const month = String(d.getMonth() + 1).padStart(2, "0");
      const day = String(d.getDate()).padStart(2, "0");

      return `${year}-${month}-${day}`;
    };

    const yesterdayDateString = getYesterdayDateString();

    const filteredTasks = userTasks.filter((task) => {
      if (task.dateCreated) {

        const taskDateString = new Date(task.dateCreated).toLocaleDateString('en-CA');

        return taskDateString === yesterdayDateString;
      }
      return false;
    });

    setPrevDayTasks(filteredTasks);
  }, [userTasks]);

  const getDailyProgress = () => {
    const allTaskCount = prevDayTasks.length;
    const completedTask = prevDayTasks.filter((task) => task.completedStatus);
    const completedCount = completedTask.length;

    if (allTaskCount === 0) {
      return 0;
    }
    const taskRatio = completedCount / allTaskCount;
    return taskRatio;
  };

  const dailyPercentage = () => {
    const ratio = getDailyProgress();
    const percentage = ratio * 100;

    return parseFloat(percentage).toFixed(1);;
  };
  return (
    <div className="stat-container">
      <h2 className="data-text">Yesterday</h2>
      <div>{dailyPercentage()}% Completed</div>
      <ProgressBar className="stats-progress" now={dailyPercentage()} />
      <p>
        ({prevDayTasks.filter((task) => task.completedStatus).length} /{" "}
        {prevDayTasks.length})
      </p>
    </div>
  );
};

// Yesterday's timestamp can be generated by filtering for 100% completion of all task and displaying the completed time of the last final task
